spring.config.activate.on-profile: dev
spring.datasource:
  url: jdbc:h2:~/voucher_service
  driver-class-name: org.h2.Driver
  username: sa
  password:

spring.h2.console:
  path: /h2-console
  enabled: true
