spring.config.activate.on-profile: deploy
spring.datasource:
  url: jdbc:mysql://localhost:3306/voucher_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  username: root
  password: 1234
spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

